version: '3'
services:
  app:
    build: .
    ports:
      - "8080:5000"
    depends_on:
      - mongo
    environment:
      - FLASK_ENV=development
    networks:
      - app-network
  mongo:
    image: mongo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
