version: '3'
services:
  app:
    build: .
    ports:
      - "8312:5000"
    depends_on:
      - mongo
    environment:
      - FLASK_ENV=development
    networks:
      - app-network
  nginx:
    build: ./nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - app-network
  mongo:
    image: mongo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge