version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - FLASK_ENV=development
    networks:
      - app-network
  nginx:
    build: ./nginx
    ports:
     - '80:80'
     - '443:443'
    depends_on:
      - app
    networks:
      - app-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
